apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moc-maria-api
  namespace: moc-maria
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.mocmaria.com
      secretName: moc-maria-api-tls
  rules:
    - host: api.mocmaria.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moc-maria-api
                port:
                  number: 80
